# Generated by Django 5.0.7 on 2024-08-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwid',
            name='login',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='login',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.TextField(),
        ),
    ]
